##############################
- block:
    # Temporary workaround until ansible-modules-core PR #2613 is merged
  - include: deb-packages.yml
    when: ansible_os_family == "Debian"

  - name: Install AlertLogic Agent on CentOS/RHEL/Amazon
    package:
      name: "{{ al_agent_pkg_url }}"
      state: present
    tags: install_al_agent
    # Temporary workaround until ansible-modules-core PR #2613 is merged
    when:
      - ansible_os_family != "Debian"
      - ansible_os_family != "Suse"

  - name: Install AlertLogic Agent on Suse
    zypper:
      name: "{{ al_agent_pkg_url }}"
      state: present
    tags: install_al_agent
    when: ansible_os_family == "Suse"

